version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./server
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - PORT=${PORT}
      - AUTO_CLOSE_ENABLED=${AUTO_CLOSE_ENABLED}
      - CONFIDENCE_THRESHOLD=${CONFIDENCE_THRESHOLD}
      - STUB_MODE=${STUB_MODE}
      - SEED_ON_START=${SEED_ON_START}
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  client:
    build: ./client
    environment:
      - VITE_API_BASE=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo_data:
